# Generated by Django 3.1.4 on 2020-12-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201224_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='al',
            new_name='album',
        ),
    ]
